"""
flags.py — maps country names to flag emojis.
Covers all 2026 World Cup qualified nations.
"""

FLAGS = {
    # Group A / USA host
    "United States": "🇺🇸",
    "USA": "🇺🇸",
    # Group nations (all 48 teams)
    "Mexico": "🇲🇽",
    "Canada": "🇨🇦",
    "Argentina": "🇦🇷",
    "Brazil": "🇧🇷",
    "France": "🇫🇷",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Germany": "🇩🇪",
    "Spain": "🇪🇸",
    "Portugal": "🇵🇹",
    "Netherlands": "🇳🇱",
    "Holland": "🇳🇱",
    "Belgium": "🇧🇪",
    "Italy": "🇮🇹",
    "Croatia": "🇭🇷",
    "Morocco": "🇲🇦",
    "Senegal": "🇸🇳",
    "Japan": "🇯🇵",
    "South Korea": "🇰🇷",
    "Korea Republic": "🇰🇷",
    "Australia": "🇦🇺",
    "Uruguay": "🇺🇾",
    "Colombia": "🇨🇴",
    "Ecuador": "🇪🇨",
    "Chile": "🇨🇱",
    "Peru": "🇵🇪",
    "Venezuela": "🇻🇪",
    "Bolivia": "🇧🇴",
    "Paraguay": "🇵🇾",
    "Saudi Arabia": "🇸🇦",
    "Iran": "🇮🇷",
    "Australia": "🇦🇺",
    "New Zealand": "🇳🇿",
    "Nigeria": "🇳🇬",
    "Ghana": "🇬🇭",
    "Ivory Coast": "🇨🇮",
    "Cameroon": "🇨🇲",
    "Egypt": "🇪🇬",
    "Algeria": "🇩🇿",
    "Tunisia": "🇹🇳",
    "South Africa": "🇿🇦",
    "Serbia": "🇷🇸",
    "Switzerland": "🇨🇭",
    "Poland": "🇵🇱",
    "Denmark": "🇩🇰",
    "Austria": "🇦🇹",
    "Hungary": "🇭🇺",
    "Czech Republic": "🇨🇿",
    "Slovakia": "🇸🇰",
    "Romania": "🇷🇴",
    "Ukraine": "🇺🇦",
    "Turkey": "🇹🇷",
    "Greece": "🇬🇷",
    "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "Sweden": "🇸🇪",
    "Norway": "🇳🇴",
    "Finland": "🇫🇮",
    "Russia": "🇷🇺",
    "China": "🇨🇳",
    "Indonesia": "🇮🇩",
    "Thailand": "🇹🇭",
    "Vietnam": "🇻🇳",
    "Iraq": "🇮🇶",
    "Jordan": "🇯🇴",
    "Qatar": "🇶🇦",
    "United Arab Emirates": "🇦🇪",
    "Costa Rica": "🇨🇷",
    "Panama": "🇵🇦",
    "Honduras": "🇭🇳",
    "Jamaica": "🇯🇲",
    "Guatemala": "🇬🇹",
    "Cuba": "🇨🇺",
    "Haiti": "🇭🇹",
    "Trinidad and Tobago": "🇹🇹",
    "Concacaf": "🌎",
    # Historic names used in old WC data
    "West Germany": "🇩🇪",
    "East Germany": "🇩🇪",
    "Soviet Union": "🇷🇺",
    "Yugoslavia": "🇷🇸",
    "Czechoslovakia": "🇨🇿",
    "Zaire": "🇨🇩",
    "North Korea": "🇰🇵",
    "Republic of Ireland": "🇮🇪",
    "Ireland": "🇮🇪",
    "Bulgaria": "🇧🇬",
    "Sweden": "🇸🇪",
    "Bolivia": "🇧🇴",
    "Cuba": "🇨🇺",
    "Dutch East Indies": "🇮🇩",
    "Romania": "🇷🇴",
}


def get_flag(country_name):
    """Returns flag emoji for a country, or 🏳 if not found."""
    return FLAGS.get(country_name, "🏳️")
